<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1561527252800' stop='1561527314334'>
    <name>Login MyStake Application</name>
    <title>Login MyStake Application</title>
    <test-cases>
        <test-case start='1561527252801' status='passed' stop='1561527274740'>
            <name>Verify Successful Login</name>
            <title>Verify Successful Login</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='84797856-7c76-45f6-ae78-8c625598dc7b-attachment.png' type='image/png' size='17546'/>
            </attachments>
        </test-case>
        <test-case start='1561527274740' status='failed' stop='1561527314333'>
            <name>Verify Invalid Credentials</name>
            <title>Verify Invalid Credentials</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='bc0c4bac-32f8-4193-8b22-8d270d4d6521-attachment.png' type='image/png' size='27949'/>
            </attachments>
            <failure>
                <message>Expected false to be true.</message>
                <stack-trace>Error: Failed expectation
                    at UserContext.&lt;anonymous> (/Users/Progressio/Documents/Protractor/e2e/test_scripts/login.tests.ts:36:24)
                    at step (/Users/Progressio/Documents/Protractor/outputjs/test_scripts/login.tests.js:32:23)
                    at Object.next (/Users/Progressio/Documents/Protractor/outputjs/test_scripts/login.tests.js:13:53)
                    at fulfilled (/Users/Progressio/Documents/Protractor/outputjs/test_scripts/login.tests.js:4:58)
                    at process._tickCallback (internal/process/next_tick.js:68:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>